all: linked_list.c linked_list.h doubly_linked_list.c doubly_linked_list.h
	gcc -g -O0 -Wall -Wextra linked_list.c -o linked_list
	gcc -g -O0 -Wall -Wextra doubly_linked_list.c -o doubly_linked_list
.PHONY: clean
clean:
	rm linked_list
